/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-surface": "#0b1c30",
        "secondary": "#605e5e",
        "surface-container-low": "#eff4ff",
        "surface-container-lowest": "#ffffff",
        "primary-fixed": "#ffdad7",
        "on-primary": "#ffffff",
        "outline-variant": "#e4beba",
        "on-tertiary": "#ffffff",
        "tertiary-fixed-dim": "#c6c6c9",
        "on-secondary-fixed-variant": "#484647",
        "primary-fixed-dim": "#ffb3ae",
        "tertiary": "#5a5c5e",
        "surface-variant": "#d3e4fe",
        "on-secondary-fixed": "#1c1b1c",
        "secondary-fixed": "#e6e1e1",
        "secondary-fixed-dim": "#cac5c6",
        "surface-tint": "#ba1724",
        "inverse-surface": "#213145",
        "surface-bright": "#f8f9ff",
        "surface-container-high": "#dce9ff",
        "outline": "#8f6f6d",
        "surface-container": "#e5eeff",
        "on-secondary": "#ffffff",
        "error": "#ba1a1a",
        "surface-dim": "#cbdbf5",
        "inverse-primary": "#ffb3ae",
        "on-tertiary-fixed": "#1a1c1e",
        "error-container": "#ffdad6",
        "on-primary-fixed-variant": "#930014",
        "secondary-container": "#e6e1e1",
        "on-background": "#0b1c30",
        "on-error-container": "#93000a",
        "on-secondary-container": "#666464",
        "on-primary-container": "#fffbff",
        "on-error": "#ffffff",
        "surface-container-highest": "#d3e4fe",
        "on-surface-variant": "#5b403e",
        "on-tertiary-container": "#fcfcff",
        "surface": "#f8f9ff",
        "primary-container": "#db3237",
        "tertiary-container": "#737577",
        "on-primary-fixed": "#410004",
        "tertiary-fixed": "#e2e2e5",
        "on-tertiary-fixed-variant": "#454749",
        "inverse-on-surface": "#eaf1ff",
        "background": "#f8f9ff",
        "primary": "#b71422",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        "2xl": "1rem",
        "3xl": "1.5rem",
        full: "9999px",
      },
      spacing: {
        "margin-desktop": "80px",
        "stack-md": "16px",
        "stack-sm": "8px",
        "gutter": "24px",
        "section-padding": "120px",
        "container-max": "1280px",
        "margin-mobile": "20px",
        "stack-lg": "32px",
      },
      maxWidth: {
        "container-max": "1280px",
      },
      fontFamily: {
        "headline-lg": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "headline-md": ["Inter", "sans-serif"],
        "headline-xl": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "label-bold": ["Inter", "sans-serif"],
        "headline-lg-mobile": ["Inter", "sans-serif"],
      },
      fontSize: {
        "headline-lg": ["40px", { lineHeight: "1.2", letterSpacing: "-0.01em", fontWeight: "700" }],
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
        "headline-md": ["24px", { lineHeight: "1.4", fontWeight: "600" }],
        "headline-xl": ["64px", { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "800" }],
        "body-md": ["16px", { lineHeight: "1.5", fontWeight: "400" }],
        "label-bold": ["14px", { lineHeight: "1", letterSpacing: "0.05em", fontWeight: "600" }],
        "headline-lg-mobile": ["32px", { lineHeight: "1.2", fontWeight: "700" }],
      },
    },
  },
  plugins: [],
};
